name: Push image on dockerhub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build Docker Image
        run: |
          docker build -t azkadevops/react:1.6 .
      - name: push Docker Image
        run: |
          docker login --username azkadevops --password a01m132806
          docker push azkadevops/react:1.6


# name: CI

# on:
#   push:
#     branches:
#       - main

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Setup Node.js
#         uses: actions/setup-node@v2
#         with:
#           node-version: '16'

#       - name: Install dependencies
#         run: npm install

#       - name: Build
#         run: npm run build

#       - name: Test
#         run: npm test
